<a href="https://colab.research.google.com/github/ssmandal31/santa_rep/blob/master/CTG_titanic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
# Code to read csv file into colaboratory:
!pip install -U -q PyDrive
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials

In [0]:
#STEP-2: Autheticate E-Mail ID

auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

In [0]:
#STEP-3: Get File from Drive using file-ID

#2.1 Get the file
downloaded = drive.CreateFile({'id':'1Prgf4GxMqDEIRtBXR5BhH8oWtQ8mHekO'}) # replace the id with id of file you want to access
downloaded.GetContentFile('titanic.csv') 

In [0]:
# Import required libraries
import pandas as pd
import numpy as np 
import seaborn as sns
import matplotlib.pyplot as plt
import sklearn
from sklearn.neural_network import MLPClassifier
from sklearn.neural_network import MLPRegressor

# Import necessary modules
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from math import sqrt
from sklearn.metrics import r2_score 

In [7]:
df = sns.load_dataset('titanic') 
print(df.shape)
df.describe().transpose()

(891, 15)


count       mean        std   min      25%      50%   75%       max
survived  891.0   0.383838   0.486592  0.00   0.0000   0.0000   1.0    1.0000
pclass    891.0   2.308642   0.836071  1.00   2.0000   3.0000   3.0    3.0000
age       714.0  29.699118  14.526497  0.42  20.1250  28.0000  38.0   80.0000
sibsp     891.0   0.523008   1.102743  0.00   0.0000   0.0000   1.0    8.0000
parch     891.0   0.381594   0.806057  0.00   0.0000   0.0000   0.0    6.0000
fare      891.0  32.204208  49.693429  0.00   7.9104  14.4542  31.0  512.3292

In [8]:
df.head()

survived  pclass     sex   age  ...  deck  embark_town  alive  alone
0         0       3    male  22.0  ...   NaN  Southampton     no  False
1         1       1  female  38.0  ...     C    Cherbourg    yes  False
2         1       3  female  26.0  ...   NaN  Southampton    yes   True
3         1       1  female  35.0  ...     C  Southampton    yes  False
4         0       3    male  35.0  ...   NaN  Southampton     no   True

[5 rows x 15 columns]

In [9]:
target_column = ['survived'] 
predictors = list(set(list(df.columns))-set(target_column))
#df[predictors] = df[predictors]/df[predictors].max()
#df.describe().transpose()
df[predictors]

embark_town   age  sibsp     sex  ...  pclass alive embarked  alone
0    Southampton  22.0      1    male  ...       3    no        S  False
1      Cherbourg  38.0      1  female  ...       1   yes        C  False
2    Southampton  26.0      0  female  ...       3   yes        S   True
3    Southampton  35.0      1  female  ...       1   yes        S  False
4    Southampton  35.0      0    male  ...       3    no        S   True
..           ...   ...    ...     ...  ...     ...   ...      ...    ...
886  Southampton  27.0      0    male  ...       2    no        S   True
887  Southampton  19.0      0  female  ...       1   yes        S   True
888  Southampton   NaN      1  female  ...       3    no        S  False
889    Cherbourg  26.0      0    male  ...       1   yes        C   True
890   Queenstown  32.0      0    male  ...       3    no        Q   True

[891 rows x 14 columns]

In [10]:
X = df[predictors].values
y = df[target_column].values

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=40)
print(X_train.shape); print(X_test.shape)

(712, 14)
(179, 14)


In [11]:
from sklearn.neural_network import MLPClassifier

mlp = MLPClassifier(hidden_layer_sizes=(8,8,8), activation='relu', solver='adam', max_iter=5000)
mlp.fit(X_train,y_train)

predict_train = mlp.predict(X_train)
predict_test = mlp.predict(X_test)


ValueError: ignored

In [0]:
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_train,predict_train))
#print(classification_report(y_train,predict_train))

[[1261   47   11]
 [ 111  121    4]
 [  19   13  113]]


In [0]:
print(confusion_matrix(y_test,predict_test))
#print(classification_report(y_test,predict_test))

[[317  17   2]
 [ 24  32   3]
 [  5   4  22]]
